### ISSUE TITLE
Connection lost: The server closed the connection - vanilla

### ISSUE THREAD

**Issue by phpmydev** [mysqljs/mysql#1889]
Hi Doug!
I have the following code:
var mysql = require('mysql');
var con = mysql.createConnection({
  host: "192.168.0.46",
  user: "SHARED",
  password: "Pjh",
  database: "SHARED"
});

con.connect(function(err) {
  if (err) return err;
  con.query("SELECT USERID FROM TBL_USER_LOCAL WHERE USERNAME = 'someuser'", function (err, result, fields) {
    if (err) return err;
    console.log(result);
  });
});

The connection gets closed if the server is offline - I am calling this from a different server than the db is running on.  The node server crashes if the above is true.  Any ideas how I can keep the node server running (this node server just listens for connections to several mysql servers) and if one is down, this code causes the crash of node.

I hope I have been clear?  Thank you!

**Comment by phpmydev** [comment]
Just to be clear, this file is called from app.js dynamically and is otherwise standalone.

**Comment by dougwilson** [comment]
So I ran your Node.js code above connected to a MySQL server.  After shutting down the MySQL server your script exits, but thr reason it exits is because the only thing in yiur code above that was preventing it frlm exiting was the open TCP connections.  Onve that was closed, there is no longer anything keeping the event loop running.

I'm not sure why you would want to keep that code running after it completed, though, because it will never do anythinf after the query result is logged.

I hope this helps explain why your script above stops running when the MySQL server goes offline!

**Comment by dougwilson** [comment]
I sse you responded with additional information while I was running your code and responding. I can help with something else, but I only have the provided information to help with. It sounds like you have some more things going on in your code. I can help with more, but without knowing what the code is I'm not sure what would be happening.

**Comment by dougwilson** [comment]
If it helps as well, here is the documentation whixh explains error handing in this module: https://github.com/mysqljs/mysql/blob/master/Readme.md#error-handling

**Comment by phpmydev** [comment]
this code above gets called when and only when a server is down.  
app.post('/cs',function(req,res){
	var status;
	if(req.session_state.user){
		var resArray = {};
		var hosts = req.body.server;
		var node;
		//~ node = require('./chk46.js');
		//~ console.log(node);
		hosts.forEach(function(item) {
			if(fs.existsSync('chk'+item[0].split('.')[3]+'.js')){

//'chk'+item[0].split('.')[3]+'.js'
//here the file in question gets called


				node = require('./chk'+item[0].split('.')[3]+'.js');
			}
			//~ console.log('chk'+item[0].split('.')[3]+'.js');
			console.log(node);
			var sock = new net.Socket();
			sock.setTimeout(2500);
			sock.on('connect', function() {
				resArray['status'+item[0]] = item[0]+':'+item[1]+' is up.';
				console.log(item[0]+':'+item[1]+' is up.');
				resArray[item[0]] = 'green';
				sock.destroy();
			}).on('error', function(e) {
				setTimeout(function(){
					resArray[item[0]] = 'red';
					resArray['status'+item[0]] = item[0]+':'+item[1]+' is down: ' + e.message;
					console.log(item[0]+':'+item[1]+' is down: ' + e.message);
				},1200);
			}).on('timeout', function(e) {
				setTimeout(function(){
					resArray[item[0]] = 'black';
					console.log(item[0]+':'+item[1]+' is down: timeout');
				},1200);
			}).connect(item[1], item[0]);
		});
	    setTimeout(function(){
			res.send(resArray);
		},2500);
	}
});

**Comment by dougwilson** [comment]
Hi @phpmydev thanks for that! There is a lot going on in the code, and just trying to run it has a lot of things undefined for me. Would it be possible to get the following information:

1. Version of Node.js
2. Version of this module
3. Complete code that I can copy and paste and run
4. Complete steps to reproduce your issue

Thanks! I'd love to help out, but I'm not sure what is happening without ideally being able to see. You're always welcome to debug through it and send over a pull request as well :) !

**Comment by phpmydev** [comment]
it looks like what I need to use is err.code?  I'm not sure where to use it.  before the call back or as the callback?

**Comment by dougwilson** [comment]
Hi @phpmydev there are a lot of callbacks between the code pasted so far. Which callback are you referring to?

**Comment by dougwilson** [comment]
Is chk46.js the file with the `app.post` in it or the one with MySQL code (sorry, trying to follow along). In the one with the MySQL call, your `return` statements just go nowhere, since nothing is using the return value from those functions. That wouldn't be an issue directly, though. Maybe if that is the complete file, you should probably be calling `conn.end()` in there to close down the connection, since you're not going to be using it again.

**Comment by phpmydev** [comment]
chk46 is the file I first posted with
I am used to using a pool instead of a single connection
app.js holds the second, complicated code
What I meant in the last post is maybe I should be handling the error in app.js and not chk46?

**Comment by phpmydev** [comment]
I can't really post the whole shebang, but I appreciate your responsiveness!

**Comment by dougwilson** [comment]
This module does have pooling, if you prefer to use it: https://github.com/mysqljs/mysql#pooling-connections

I'm trying to help, but just not sure why your server is crashing. Ideally I can run it so I can attach a debugger to figure it out. I did run the code initially and it closed down, and I posted why that happened, but if that's not matching what you're getting, not sure what exactly the difference is here, is all :(

**Comment by phpmydev** [comment]
the mysql server is not crashing - just stopping it in testing - it's the node server that's monitoring it that's crashing - we're on the same page right?

**Comment by dougwilson** [comment]
> the mysql server is not crashing - just stopping it in testing - it's the node server that's monitoring it that's crashing - we're on the same page right?

yea, we're on the same page. that's what I did to test your initial code: I just changed the connection to connect to my DB, ran the file, and it stayed running. Then when I stopped the MySQL server (to test this), the Node.js did close like you said. The reason it closed, though, was because the only thing that was keeping the Node.js process open was the TCP connection on the event loop -- but when I stopped the MySQL server, that closes the TCP connection, and with that closed there is no longer anything to keep the Node.js process from exiting -- Node.js will exit when there isn't anything open on the event loop.

**Comment by phpmydev** [comment]
will it just exit? or will it crash?  for me it is crashing - is it the same thing?

**Comment by phpmydev** [comment]
I'm really becoming a PITA at this point, I think! ;-)

**Comment by dougwilson** [comment]
I am just seeing a clean exit with the code. Not sure where the crash is happening. Maybe does your crash have a stack trace that comes with it? That may help figure it out.

**Comment by phpmydev** [comment]
Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/pi/Public/kv/node_modules/mysql/lib/protocol/Protocol.js:113:13)
    at Socket.<anonymous> (/home/pi/Public/kv/node_modules/mysql/lib/Connection.js:109:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by dougwilson** [comment]
Thanks! Have you tried the `con.end()` yet? That I think should fix it; not leaving the connection open hanging there if you're not going to re-use it. Just add it within the callback of your `con.query()`.

**Comment by phpmydev** [comment]
hmm,  it would seem that I clicking  a button when I should not!  I don't know If that is the solution, but I will bid you adieu for now - thank you!  I did do the con.end btw - it still crashed, but I think only by clicking wrongly!
